# prometheus.yml
global:
  scrape_interval: 15s # How often to scrape targets

scrape_configs:
  # This job scrapes Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # THIS IS THE JOB FOR OUR PYTHON APP
  - job_name: 'python-app'
    static_configs:
      # We'll run our Flask app on port 5000
      # 'host.docker.internal' is a special name that lets the
      # Docker container find services running on your computer
      - targets: ['host.docker.internal:5020']